language: php

php:
  - 7.3.5

env:
  - SYMFONY_VERSION=4.3.*
  - SYMFONY_VERSION=dev-master

services:
  - postgresql

before_script:
  - composer install
  - psql -c "CREATE DATABASE slamquiz;" -U postgres
  - psql -c "CREATE ROLE slamquiz password 'root' login;" -U postgres
  - psql -c "GRANT ALL ON DATABASE slamquiz TO slamquiz WITH GRANT OPTION;" -U postgres
  - php bin/console doctrine:migrations:migrate -n --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script: phpunit --coverage-text