language: php

php:
  - 7.3.5

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE slamquiz;" -U postgres
  - psql -c "CREATE ROLE slamquiz password 'root' login;" -U postgres
  - psql -c "GRANT ALL ON DATABASE slamquiz TO slamquiz WITH GRANT OPTION;" -U postgres

env:
  - DATABASE_URL="pgsql://slamquiz:db_password@127.0.0.1:5432/slamquiz"

script:
  - composer install
  - php bin/console doctrine:migrations:migrate -n
  - php bin/console doctrine:fixtures:load -n
  - php bin/phpunit