language: php

php:
  - 7.3.5

env:
  - SYMFONY_VERSION=4.3.*
  - SYMFONY_VERSION=dev-master

services:
  - postgresql

before_script:
  - composer install
  - sudo -i -u postgres
  - CREATE DATABASE slamquiz;
  - CREATE ROLE slamquiz password 'db_password' login;
  - GRANT ALL ON DATABASE slamquiz TO slamquiz WITH GRANT OPTION;
  - \q
  - php bin/console doctrine:migrations:migrate
  - -> y
  - php bin/console doctrine:fixtures:load
  - -> y

script: phpunit --coverage-text